# Dockerfile para configurar Apache y agregar el archivo de configuración personalizado

FROM httpd:2.4

# Copiar los archivos HTML al directorio de documentos de Apache
COPY ./public-html/ /usr/local/apache2/htdocs/

# Copiar el archivo de configuración personalizado
COPY ./my-httpd.conf /usr/local/apache2/conf/my-httpd.conf

EXPOSE 80

